/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PixelGridMakerRouteImport } from './routes/pixel-grid-maker'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as InstagramGridMakerRouteImport } from './routes/instagram-grid-maker'
import { Route as DrawingGridMakerRouteImport } from './routes/drawing-grid-maker'
import { Route as CrossStitchGridMakerRouteImport } from './routes/cross-stitch-grid-maker'
import { Route as CrochetGridMakerRouteImport } from './routes/crochet-grid-maker'
import { Route as AddGridToPhotoRouteImport } from './routes/add-grid-to-photo'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as legalsTermsRouteImport } from './routes/(legals)/terms'
import { Route as legalsPrivacyRouteImport } from './routes/(legals)/privacy'
import { Route as legalsCookieRouteImport } from './routes/(legals)/cookie'
import { Route as LocaleSlugRouteImport } from './routes/$locale/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PixelGridMakerRoute = PixelGridMakerRouteImport.update({
  id: '/pixel-grid-maker',
  path: '/pixel-grid-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramGridMakerRoute = InstagramGridMakerRouteImport.update({
  id: '/instagram-grid-maker',
  path: '/instagram-grid-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingGridMakerRoute = DrawingGridMakerRouteImport.update({
  id: '/drawing-grid-maker',
  path: '/drawing-grid-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossStitchGridMakerRoute = CrossStitchGridMakerRouteImport.update({
  id: '/cross-stitch-grid-maker',
  path: '/cross-stitch-grid-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const CrochetGridMakerRoute = CrochetGridMakerRouteImport.update({
  id: '/crochet-grid-maker',
  path: '/crochet-grid-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const AddGridToPhotoRoute = AddGridToPhotoRouteImport.update({
  id: '/add-grid-to-photo',
  path: '/add-grid-to-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsTermsRoute = legalsTermsRouteImport.update({
  id: '/(legals)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsPrivacyRoute = legalsPrivacyRouteImport.update({
  id: '/(legals)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsCookieRoute = legalsCookieRouteImport.update({
  id: '/(legals)/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSlugRoute = LocaleSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/add-grid-to-photo': typeof AddGridToPhotoRoute
  '/crochet-grid-maker': typeof CrochetGridMakerRoute
  '/cross-stitch-grid-maker': typeof CrossStitchGridMakerRoute
  '/drawing-grid-maker': typeof DrawingGridMakerRoute
  '/instagram-grid-maker': typeof InstagramGridMakerRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/pixel-grid-maker': typeof PixelGridMakerRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/api/ping': typeof ApiPingRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-grid-to-photo': typeof AddGridToPhotoRoute
  '/crochet-grid-maker': typeof CrochetGridMakerRoute
  '/cross-stitch-grid-maker': typeof CrossStitchGridMakerRoute
  '/drawing-grid-maker': typeof DrawingGridMakerRoute
  '/instagram-grid-maker': typeof InstagramGridMakerRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/pixel-grid-maker': typeof PixelGridMakerRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/api/ping': typeof ApiPingRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/add-grid-to-photo': typeof AddGridToPhotoRoute
  '/crochet-grid-maker': typeof CrochetGridMakerRoute
  '/cross-stitch-grid-maker': typeof CrossStitchGridMakerRoute
  '/drawing-grid-maker': typeof DrawingGridMakerRoute
  '/instagram-grid-maker': typeof InstagramGridMakerRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/pixel-grid-maker': typeof PixelGridMakerRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/(legals)/cookie': typeof legalsCookieRoute
  '/(legals)/privacy': typeof legalsPrivacyRoute
  '/(legals)/terms': typeof legalsTermsRoute
  '/api/ping': typeof ApiPingRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/add-grid-to-photo'
    | '/crochet-grid-maker'
    | '/cross-stitch-grid-maker'
    | '/drawing-grid-maker'
    | '/instagram-grid-maker'
    | '/manifest.json'
    | '/pixel-grid-maker'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/$slug'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/api/ping'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-grid-to-photo'
    | '/crochet-grid-maker'
    | '/cross-stitch-grid-maker'
    | '/drawing-grid-maker'
    | '/instagram-grid-maker'
    | '/manifest.json'
    | '/pixel-grid-maker'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/$slug'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/api/ping'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/add-grid-to-photo'
    | '/crochet-grid-maker'
    | '/cross-stitch-grid-maker'
    | '/drawing-grid-maker'
    | '/instagram-grid-maker'
    | '/manifest.json'
    | '/pixel-grid-maker'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/$slug'
    | '/(legals)/cookie'
    | '/(legals)/privacy'
    | '/(legals)/terms'
    | '/api/ping'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AboutRoute: typeof AboutRoute
  AddGridToPhotoRoute: typeof AddGridToPhotoRoute
  CrochetGridMakerRoute: typeof CrochetGridMakerRoute
  CrossStitchGridMakerRoute: typeof CrossStitchGridMakerRoute
  DrawingGridMakerRoute: typeof DrawingGridMakerRoute
  InstagramGridMakerRoute: typeof InstagramGridMakerRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  PixelGridMakerRoute: typeof PixelGridMakerRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  legalsCookieRoute: typeof legalsCookieRoute
  legalsPrivacyRoute: typeof legalsPrivacyRoute
  legalsTermsRoute: typeof legalsTermsRoute
  ApiPingRoute: typeof ApiPingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pixel-grid-maker': {
      id: '/pixel-grid-maker'
      path: '/pixel-grid-maker'
      fullPath: '/pixel-grid-maker'
      preLoaderRoute: typeof PixelGridMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-grid-maker': {
      id: '/instagram-grid-maker'
      path: '/instagram-grid-maker'
      fullPath: '/instagram-grid-maker'
      preLoaderRoute: typeof InstagramGridMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawing-grid-maker': {
      id: '/drawing-grid-maker'
      path: '/drawing-grid-maker'
      fullPath: '/drawing-grid-maker'
      preLoaderRoute: typeof DrawingGridMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-stitch-grid-maker': {
      id: '/cross-stitch-grid-maker'
      path: '/cross-stitch-grid-maker'
      fullPath: '/cross-stitch-grid-maker'
      preLoaderRoute: typeof CrossStitchGridMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crochet-grid-maker': {
      id: '/crochet-grid-maker'
      path: '/crochet-grid-maker'
      fullPath: '/crochet-grid-maker'
      preLoaderRoute: typeof CrochetGridMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-grid-to-photo': {
      id: '/add-grid-to-photo'
      path: '/add-grid-to-photo'
      fullPath: '/add-grid-to-photo'
      preLoaderRoute: typeof AddGridToPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/terms': {
      id: '/(legals)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/privacy': {
      id: '/(legals)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/cookie': {
      id: '/(legals)/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof legalsCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$slug': {
      id: '/$locale/$slug'
      path: '/$slug'
      fullPath: '/$locale/$slug'
      preLoaderRoute: typeof LocaleSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleSlugRoute: typeof LocaleSlugRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleSlugRoute: LocaleSlugRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AboutRoute: AboutRoute,
  AddGridToPhotoRoute: AddGridToPhotoRoute,
  CrochetGridMakerRoute: CrochetGridMakerRoute,
  CrossStitchGridMakerRoute: CrossStitchGridMakerRoute,
  DrawingGridMakerRoute: DrawingGridMakerRoute,
  InstagramGridMakerRoute: InstagramGridMakerRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  PixelGridMakerRoute: PixelGridMakerRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  legalsCookieRoute: legalsCookieRoute,
  legalsPrivacyRoute: legalsPrivacyRoute,
  legalsTermsRoute: legalsTermsRoute,
  ApiPingRoute: ApiPingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
